services:

  chatserver-a:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - elasticmq
      - dynamodb-local

  chatserver-b:
    build: .
    ports:
      - "8081:8080"
    env_file: .env
    depends_on:
      - elasticmq
      - dynamodb-local

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
