services:

  chatserver:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      retries: 3